http:
  services:
    authe:
      loadBalancer:
        servers:
          - url: "{{ env "AUTHGATE_AUTHE_URL" | default "http://localhost:23000" }}"
    autho:
      loadBalancer:
        servers:
          - url: "{{ env "AUTHGATE_AUTHO_URL" | default "http://localhost:24000" }}"
